name: Build APK

on:
  push:
    branches: [ main ] # Or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17 # Or your preferred JDK version
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # Or 'zulu', 'adopt', etc.

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          build-tools-version: '33.0.0' # Or latest stable version
          api-level: '33' # Or your target API level
          ndk-version: 'latest' # Or a specific NDK version if needed

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug # Or ./gradlew assembleRelease for a release build

      - name: Upload APK
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: app-debug.apk # Or a more descriptive name
          path: app/build/outputs/apk/debug/app-debug.apk # Adjust path if necessary
